repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: env/bin/black
        language: python
        types: [python]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: env/bin/pytest
        language: python
        types: [python]
        pass_filenames: false
